spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ukwEecKhMrJzOdjwpJfB
            client-secret: au4WnhNLFn
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
  #          google:
  #            clientId: 533736617983-4jfhmdp450ii47sg8eb8uni668ikkkpp.apps.googleusercontent.com
  #            clientSecret: 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
  #            scope: profile,email


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://springdb.ckwyhhagz0nl.ap-northeast-2.rds.amazonaws.com:3306/survey-proj
    username: root
    password: tjfanswhtk10!

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

# 파일 저장 경로 설정
file:
  upload-dir: C:\Users\User\Desktop\survey-management-backend\src\main\java\com\douzone\surveymanagement\common\utils\image

# MultipartResolver 설정
spring.servlet.multipart.max-file-size: 10MB
spring.servlet.multipart.max-request-size: 10MB
spring.servlet.multipart.resolve-lazily: true
spring.servlet.multipart.file-size-threshold: 0
spring.servlet.multipart.location: /tmp
